# Generated by Django 4.1 on 2022-12-28 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccount',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('opId', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PendingAccount',
                'verbose_name_plural': 'PendingAccounts',
                'db_table': 'pendingAccount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationSummary',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('opId', models.CharField(blank=True, max_length=255, null=True)),
                ('emitter', models.CharField(blank=True, max_length=255, null=True)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('emitterId', models.CharField(blank=True, max_length=255, null=True)),
                ('payerId', models.CharField(blank=True, max_length=255, null=True)),
                ('futureValue', models.FloatField(default=0)),
                ('payedPercent', models.FloatField(default=0)),
                ('valueToDiscount', models.FloatField(default=0)),
                ('discountTax', models.FloatField(default=0)),
                ('discountedDays', models.IntegerField(blank=True, default=0, null=True)),
                ('SMDiscount', models.FloatField(default=0)),
                ('investorValue', models.FloatField(default=0)),
                ('investorDiscount', models.FloatField(default=0)),
                ('commissionValueBeforeTaxes', models.FloatField(default=0)),
                ('operationValue', models.FloatField(default=0)),
                ('tableCommission', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('retIva', models.FloatField(default=0)),
                ('retIca', models.FloatField(default=0)),
                ('retFte', models.FloatField(default=0)),
                ('billValue', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('pendingToDeposit', models.FloatField(default=0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NegotiationSummary',
                'verbose_name_plural': 'NegotiationSummaries',
                'db_table': 'negotiationSummary',
                'ordering': ['-created_at'],
            },
        ),
    ]
