# Generated by Django 4.1 on 2022-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsummary',
            name='billId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
