# Generated by Django 4.1 on 2022-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_negotiationsummary_billid'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsummary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
