# Generated by Django 4.1 on 2022-12-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_negotiationsummary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationsummary',
            name='totalDiscounts',
            field=models.FloatField(default=0),
        ),
    ]
