# Generated by Django 4.1 on 2022-12-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0023_alter_accountingaccount_options_and_more'),
        ('client', '0057_alter_client_user'),
        ('report', '0004_negotiationsummary_totaldiscounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaccount',
            name='accountingControl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.accountingaccount'),
        ),
        migrations.AddField(
            model_name='pendingaccount',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
