# Generated by Django 4.1 on 2022-12-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0023_alter_accountingaccount_options_and_more'),
        ('report', '0005_pendingaccount_accountingcontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaccount',
            name='typeExpenditure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.typeexpenditure'),
        ),
    ]
