# Generated by Django 4.1 on 2023-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_sellorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationsummary',
            name='billId',
            field=models.CharField(default=None, error_messages={'required': 'Factura requerida'}, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='date',
            field=models.DateField(default=None, error_messages={'required': 'Fecha requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='discountedDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='emitter',
            field=models.CharField(default=None, error_messages={'required': 'Emisor requerido'}, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='emitterId',
            field=models.CharField(default=None, error_messages={'required': 'Emisor requerido'}, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='observations',
            field=models.TextField(default=None, error_messages={'required': 'Observaciones requeridas'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='opId',
            field=models.CharField(default=None, error_messages={'required': 'Operación requerida'}, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='payer',
            field=models.CharField(default=None, error_messages={'required': 'Pagador requerido'}, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='payerId',
            field=models.CharField(default=None, error_messages={'required': 'Pagador requerido'}, max_length=255),
            preserve_default=False,
        ),
    ]
