# Generated by Django 4.1 on 2023-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_negotiationsummary_billid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationsummary',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
