# Generated by Django 4.1 on 2023-01-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_negotiationsummary_totaldeposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationsummary',
            name='discountedDays',
            field=models.CharField(error_messages={'required': 'Porcentaje pagado requerido'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='negotiationsummary',
            name='payedPercent',
            field=models.CharField(error_messages={'required': 'Porcentaje pagado requerido'}, max_length=255),
        ),
    ]
