# Generated by Django 4.1.7 on 2023-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_negotiationsummary_discounteddays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='emitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
