# Generated by Django 4.1.7 on 2023-02-16 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_preoperation_insufficientaccountbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0012_sellorder_emitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrderOperation',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellOrderOperations', to='operation.preoperation')),
                ('sellOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellOrderOperations', to='report.sellorder')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sellOrderOperation',
                'verbose_name_plural': 'sellOrderOperations',
                'db_table': 'sellOrderOperation',
                'ordering': ['-created_at'],
            },
        ),
    ]
