# Generated by Django 4.1.7 on 2023-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_sellorderoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorder',
            old_name='emitter',
            new_name='approveCode',
        ),
        migrations.AddField(
            model_name='sellorder',
            name='rejectCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
