# Generated by Django 4.1.7 on 2023-02-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_alter_riskprofile_account_number_and_more'),
        ('report', '0014_rename_emitter_sellorder_approvecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
