# Generated by Django 4.1.7 on 2023-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_sellorderoperation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellorderoperation',
            name='status',
        ),
        migrations.AddField(
            model_name='sellorder',
            name='opId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
