class NotificationEvent:
    BILL_EXPIRED = "BILL_EXPIRED"
    BILL_EXPIRING = "BILL_EXPIRING"
    PREOPERATION_PENDING_APPROVAL = "PREOPERATION_PENDING_APPROVAL"
    ELECTRONIC_SIGNATURE_PENDING = "ELECTRONIC_SIGNATURE_PENDING"
    OPERATION_EXPIRING = "OPERATION_EXPIRING"