# Generated by Django 4.1 on 2022-09-15 19:19

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typeBill')
        model.objects.create(id='fdb5feb4-24e9-41fc-9689-31aff60b76c9', description='FV')
        model.objects.create(id='a7c70741-8c1a-4485-8ed4-5297e54a978a', description='FV-TV')
        model.objects.create(id='29113618-6ab8-4633-aa8e-b3d6f242e8a4', description='ENDOSADA')

    dependencies = [
        ('misc', '0003_typebill'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
