# Generated by Django 4.1 on 2022-09-20 19:50

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        # departments
        model = apps.get_model('misc', 'typeOperation')
        model.objects.create(id='4ba7b2ef-07b1-47bd-8239-e3ce16ea2e94', description='Compra Titulo')

    dependencies = [
        ('misc', '0005_typeoperation'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
