# Generated by Django 4.1 on 2022-09-27 21:40

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typeEvent')
        model.objects.create(id='07c61f28-83f8-4f91-b965-f685f86cf6bf', code='030' ,description='Acuse de recibo de la Factura Electrónica de Venta')
        model.objects.create(id='141db270-23ec-49c1-87a7-352d5413d309', code='032' ,description='Recibo del bien o prestación del servicio')
        model.objects.create(id='c508eeb3-e0e8-48e8-a26f-5295f95c1f1f', code='033' ,description='Aceptación expresa de la Factura Electrónica de Venta')

    dependencies = [
        ('misc', '0007_typeevent'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
