# Generated by Django 4.1 on 2022-10-03 13:50

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typeReceipt')
        model.objects.create(id='db1d1fa4-e467-4fde-9aee-bbf4008d688b',description='Cancelado Vigente')
        model.objects.create(id='3d461dea-0545-4a92-a847-31b8327bf033',description='Cancelado Anticipado')
        model.objects.create(id='62b0ca1e-f999-4a76-a07f-be1fe4f38cfb',description='Cancelado Vencido')
        model.objects.create(id='d40e91b1-fb6c-4c61-9da8-78d4f258181d',description='Parcial vigente')
        model.objects.create(id='edd99cf7-6f47-4c82-a4fd-f13b4c60a0c0',description='Parcial anticipado')
        model.objects.create(id='ed85d2bc-1a4b-45ae-b2fd-f931527d9f7f',description='Parcial vencido')

    dependencies = [
        ('misc', '0009_typereceipt'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
