# Generated by Django 4.1 on 2022-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_accountingaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingaccount',
            old_name='number',
            new_name='accountNumber',
        ),
        migrations.AddField(
            model_name='accountingaccount',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
