# Generated by Django 4.1 on 2022-10-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0017_add_type_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReceiptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeReceiptLog',
                'verbose_name_plural': 'typeReceiptLog',
                'db_table': 'typeReceiptLog',
            },
        ),
        migrations.CreateModel(
            name='TypePeriodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typePeriodLog',
                'verbose_name_plural': 'typePeriodsLog',
                'db_table': 'typePeriodsLog',
            },
        ),
        migrations.CreateModel(
            name='TypeOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeOperationLog',
                'verbose_name_plural': 'typeOperationsLog',
                'db_table': 'typeOperationLog',
            },
        ),
        migrations.CreateModel(
            name='TypeIdentityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeIdentityLog',
                'verbose_name_plural': 'typeIdentitiesLog',
                'db_table': 'typeIdentitiesLog',
            },
        ),
        migrations.CreateModel(
            name='TypeExpenditureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeExpenditureLog',
                'verbose_name_plural': 'typeExpendituresLog',
                'db_table': 'typeExpendituresLog',
            },
        ),
        migrations.CreateModel(
            name='TypeEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeEventLog',
                'verbose_name_plural': 'typeEventsLog',
                'db_table': 'typeEventsLog',
            },
        ),
        migrations.CreateModel(
            name='TypeCLientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeClientLog',
                'verbose_name_plural': 'typeClientsLog',
                'db_table': 'typeClientsLog',
            },
        ),
        migrations.CreateModel(
            name='TypeBillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typeBillLog',
                'verbose_name_plural': 'typeBillLog',
                'db_table': 'typeBillLog',
            },
        ),
        migrations.CreateModel(
            name='SectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sectionLog',
                'verbose_name_plural': 'sectionsLog',
                'db_table': 'sectionsLog',
            },
        ),
        migrations.CreateModel(
            name='DepartmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'departmentLog',
                'verbose_name_plural': 'departmentsLog',
                'db_table': 'departmentsLog',
            },
        ),
        migrations.CreateModel(
            name='CityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='misc.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cityLog',
                'verbose_name_plural': 'citiesLog',
                'db_table': 'citiesLog',
            },
        ),
        migrations.CreateModel(
            name='CIIULog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='misc.activity')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='misc.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ciiuLog',
                'verbose_name_plural': 'ciiuLog',
                'db_table': 'ciiuLog',
            },
        ),
        migrations.CreateModel(
            name='BankLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bankLog',
                'verbose_name_plural': 'banksLog',
                'db_table': 'banksLog',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activityLog',
                'verbose_name_plural': 'activitiesLog',
                'db_table': 'activitiesLog',
            },
        ),
        migrations.CreateModel(
            name='AccountTypeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accountTypeLog',
                'verbose_name_plural': 'accountTypesLog',
                'db_table': 'accountTypesLog',
            },
        ),
        migrations.CreateModel(
            name='AccountingAccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('accountNumber', models.CharField(blank=True, max_length=255)),
                ('Action', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accountingAccountLog',
                'verbose_name_plural': 'accountingAccountsLog',
                'db_table': 'accountingAccountsLog',
            },
        ),
    ]
