# Generated by Django 4.1 on 2022-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'periodRange')
        model.objects.create(id='2f1d5c8d-36ef-4b1a-a76a-91b9f60363f7',description='1er semestre')
        model.objects.create(id='5d3020f0-b4ce-4ef1-b308-821fef463c95',description='2do semestre')
        model.objects.create(id='e2b93f89-dbd9-48fc-828f-f7170771c819',description='1er trimestre')
        model.objects.create(id='ec4506b5-3440-4208-85e4-3b64b80261e2',description='2do trimestre')
        model.objects.create(id='6a8a9448-854a-4353-bbb6-70c39a7678b8',description='3er trimestre')
        model.objects.create(id='3f49404f-5f2a-4ba7-ba3e-fffbc0ed8fce',description='4to trimestre')

    dependencies = [
        ('misc', '0021_periodrange'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
