# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0022_period_range_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'accountingAccount', 'verbose_name_plural': 'accountingAccounts'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['-created_at'], 'verbose_name': 'accountType', 'verbose_name_plural': 'accountTypes'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-created_at'], 'verbose_name': 'bank', 'verbose_name_plural': 'banks'},
        ),
        migrations.AlterModelOptions(
            name='ciiu',
            options={'ordering': ['-created_at'], 'verbose_name': 'ciiu', 'verbose_name_plural': 'ciiu'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created_at'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='periodrange',
            options={'ordering': ['-created_at'], 'verbose_name': 'periodRange', 'verbose_name_plural': 'periodRanges'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='typebill',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeBill', 'verbose_name_plural': 'typeBill'},
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeClient', 'verbose_name_plural': 'typeClients'},
        ),
        migrations.AlterModelOptions(
            name='typeevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeEvent', 'verbose_name_plural': 'typeEvents'},
        ),
        migrations.AlterModelOptions(
            name='typeexpenditure',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeExpenditure', 'verbose_name_plural': 'typeExpenditures'},
        ),
        migrations.AlterModelOptions(
            name='typeidentity',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeIdentity', 'verbose_name_plural': 'typeIdentities'},
        ),
        migrations.AlterModelOptions(
            name='typeoperation',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeOperation', 'verbose_name_plural': 'typeOperations'},
        ),
        migrations.AlterModelOptions(
            name='typeperiod',
            options={'ordering': ['-created_at'], 'verbose_name': 'typePeriod', 'verbose_name_plural': 'typePeriods'},
        ),
        migrations.AlterModelOptions(
            name='typereceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'typeReceipt', 'verbose_name_plural': 'typeReceipt'},
        ),
    ]
