# Generated by Django 4.1 on 2023-01-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0023_alter_accountingaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-description'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-description'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
