# Generated by Django 4.1 on 2023-01-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0024_alter_city_options_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['description'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['description'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
