# Generated by Django 4.1 on 2023-01-12 15:46

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'bank')
        model.objects.create(id='3f197066-77cd-4185-b41f-0ea45ccaed11',description='Banco Serfinanza')
        model.objects.create(id='3932db95-5ed5-4740-be7d-6e62d6bc38c5',description='No Registra')
        model.objects.create(id='149651a3-d627-45b2-95c1-bec2323e60d5',description='Small Business')
        model.objects.create(id='7dbcd53f-049c-40d1-8f35-692535839c8f',description='ol')
        model.objects.create(id='85507ced-3a2f-471c-92d7-aad3ed707a55',description='Geomatrix')
        model.objects.create(id='70dea415-25cc-442b-9a01-42ddcd0a1591',description='Servientrega')
        model.objects.create(id='32b83850-5832-4fa9-83ac-ba7ceea6e597',description='ND')
        model.objects.create(id='e241f2cb-5d0d-40a0-a13b-925031adf5f2',description='No registra endeudamiento con el sector financiero')
        model.objects.create(id='817f4e91-70c6-490a-9599-81ee1c75dd29',description='N.A')
        model.objects.create(id='aea432c1-8698-47f1-a900-d39c743a6ac7',description='Laumayer')
        model.objects.create(id='d6797dff-494f-4a1f-b515-f1d91025f68e',description='Corporacion Interactuar')
        model.objects.create(id='42b4f672-5bf3-4376-bcf3-8ca2e4cc01f5',description='Comercializadora Santander')
        model.objects.create(id='7608290a-f1f0-4c57-afb7-21b82e19aca0',description='TDH')
        model.objects.create(id='0554a011-17b1-4d69-b019-2eb4ab1a96fe',description='FINANPRIMAS')
        model.objects.create(id='bce5a238-6f43-4ee7-ba57-1b42607cf172',description='Team Foods')
        model.objects.create(id='7ef3b22a-0695-44c2-97dd-df964f749eb0',description='Finanzauto')
        model.objects.create(id='be57c937-4069-46c6-a558-69b46279e965',description='sempli')
        model.objects.create(id='af31995b-4454-43de-a6f2-249ebad4c3a9',description='NEXSYS')
        model.objects.create(id='23f52fc1-a63d-4f7a-b930-3883a9985c01',description='CLARO')
        model.objects.create(id='b7f28051-6061-487b-80ee-11422694cea4',description='Otros')
        model.objects.create(id='d1a9cf02-5fea-49e4-a553-d1b59aa6f91f',description='Granaliados')
        model.objects.create(id='a747178f-368e-4989-b3e6-d19f10d658a2',description='Giros y Finanzas')
        model.objects.create(id='2cb0ded1-4077-4f7f-9681-5ef6418f9db5',description='FINAGRO')
        model.objects.create(id='6afa9bbf-d917-4976-b91a-22d6107b944a',description='Coltefinanciera')

    dependencies = [
        ('misc', '0025_alter_city_options_alter_department_options'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
