# Generated by Django 4.1 on 2023-01-23 16:04

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typePeriod')
        model.objects.create(id='a12eec8b-06e1-4fbc-a888-d33364032151', description='Rango de fechas')

    dependencies = [
        ('misc', '0026_add_bank_values'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
