# Generated by Django 4.1 on 2023-01-23 22:04

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typeOperation')
        model.objects.create(id='0fc709f3-f1fe-4252-b483-f2ac11c1f18d', description='Recompra')     
    dependencies = [
        ('misc', '0027_add_new_type_period'),
    ]

    operations = [
    ]
