# Generated by Django 4.1 on 2023-01-24 16:42

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'receiptStatus')
        model.objects.create(id='3db5ba64-0cf8-485a-afcf-5b17bad5784d', description='Transferencia')
        model.objects.create(id='c5a11a9a-35b4-488f-929f-7fe23e80c311', description='Compensación')  
        model.objects.create(id='ea8518e8-168a-46d7-b56a-1286bf0037cd', description='Recompra')     

    dependencies = [
        ('misc', '0029_receiptstatus'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
