# Generated by Django 4.1.7 on 2023-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    def load_initial_data(apps,schema_editor):
        # type identity
        model = apps.get_model('misc', 'typeidentity')
        model.objects.create(id='cff883e6-bd88-4cad-9df2-c0e96761f234', description='Cédula de ciudadanía', abbreviation='CC')
        model.objects.create(id='198e2fda-28ee-4e87-b7f1-83601f16f188', description='Tarjeta de extranjería', abbreviation='TE')
        model.objects.create(id='2070d98f-b573-4fb1-b841-dcab929358e1', description='Cédula de extranjería', abbreviation='CE')
        model.objects.create(id='6b1a9326-00c6-4b72-a8b4-4453b889fbb7', description='NIT', abbreviation='NIT')
        model.objects.create(id='a20e1643-8d72-4551-a7ed-96dd18ce6b32', description='Pasaporte', abbreviation='PAS')
    dependencies = [
        ('misc', '0031_add_accounting_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeidentity',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunPython(load_initial_data),
    ]
