# Generated by Django 4.1.2 on 2023-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0032_typeidentity_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountId', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('gmAmount', models.FloatField()),
            ],
            options={
                'verbose_name': 'fix',
                'verbose_name_plural': 'fixes',
                'db_table': 'fixes',
                'ordering': ['accountId'],
            },
        ),
    ]
