# Generated by Django 4.1.2 on 2026-01-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0033_fixes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeevent',
            old_name='description',
            new_name='supplierDescription',
        ),
    ]
