# Generated by Django 4.1.2 on 2026-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0034_rename_description_typeevent_supplierdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeevent',
            name='dianDescription',
            field=models.TextField(blank=True),
        ),
    ]
