# Generated by Django 4.1 on 2022-09-23 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_add_type_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('document_number', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('social_reason', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('income', models.SmallIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.broker')),
                ('ciiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.ciiu')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.country')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.city')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_by', to=settings.AUTH_USER_MODEL)),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.typeclient')),
                ('type_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.typeidentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clients',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
                'ordering': ['created_at'],
            },
        ),
    ]
