# Generated by Django 4.1 on 2022-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='social_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
