# Generated by Django 4.1 on 2022-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_legalrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalrepresentative',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
