# Generated by Django 4.1 on 2022-09-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['created_at'], 'verbose_name': 'requests', 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterModelTable(
            name='request',
            table='requests',
        ),
    ]
