# Generated by Django 4.1 on 2022-09-23 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0006_add_type_operation'),
        ('client', '0009_alter_request_options_alter_request_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('gmf', models.BooleanField(default=False)),
                ('iva', models.BooleanField(default=False)),
                ('ica', models.BooleanField(default=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_rate_investor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('investor_balance', models.FloatField(default=0)),
                ('emitter_balance', models.FloatField(default=0)),
                ('payer_balance', models.FloatField(default=0)),
                ('account_number', models.CharField(max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'riskProfile',
                'verbose_name_plural': 'riskProfiles',
                'db_table': 'riskProfile',
                'ordering': ['created_at'],
            },
        ),
    ]
