# Generated by Django 4.1 on 2022-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_assets_stateofresult_patrimony_passives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='client',
        ),
        migrations.RemoveField(
            model_name='passives',
            name='client',
        ),
        migrations.RemoveField(
            model_name='patrimony',
            name='client',
        ),
        migrations.RemoveField(
            model_name='stateofresult',
            name='client',
        ),
    ]
