# Generated by Django 4.1 on 2022-09-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_remove_assets_client_remove_passives_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='period',
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='assets',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.assets'),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='passives',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.passives'),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='patrimony',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.patrimony'),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='stateOfResult',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.stateofresult'),
        ),
        migrations.CreateModel(
            name='s3',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('pdf', models.FileField(upload_to='s3')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
