# Generated by Django 4.1 on 2022-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_assets_period_alter_financialprofile_assets_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s3',
        ),
    ]
