# Generated by Django 4.1 on 2022-09-27 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_add_type_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0014_delete_s3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialprofile',
            options={'ordering': ['created_at'], 'verbose_name': 'FinancialProfiles', 'verbose_name_plural': 'FinancialProfiles'},
        ),
        migrations.AlterModelTable(
            name='financialprofile',
            table='FinancialProfiles',
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('qualitativeOverview', models.TextField()),
                ('financialAnalisis', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overviews',
                'verbose_name_plural': 'Overviews',
                'db_table': 'Overviews',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCentral',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('centralBalances', models.FloatField(default=0)),
                ('rating', models.CharField(max_length=1, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FinancialCentrals',
                'verbose_name_plural': 'FinancialCentrals',
                'db_table': 'FinancialCentrals',
                'ordering': ['created_at'],
            },
        ),
    ]
