# Generated by Django 4.1 on 2022-09-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_financialprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcentral',
            name='rating',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
