# Generated by Django 4.1 on 2022-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_financialcentral_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='social_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
