# Generated by Django 4.1 on 2022-10-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_broker_social_reason_alter_broker_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='emitter_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='investor_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payer_balance',
        ),
    ]
