# Generated by Django 4.1 on 2022-10-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0018_rename_emitter_balance_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.department'),
        ),
        #migrations.AddField(
        #    model_name='financialprofile',
        #    name='typePeriod',
        #    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.typeperiod'),
        #    preserve_default=False,
        #),
    ]
