# Generated by Django 4.1 on 2022-10-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0021_naturalclientselfmanagement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='CityClient',
            new_name='CityLC',
        ),
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='DepartmentClient',
            new_name='DepartmentLC',
        ),
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='TypeCLientC',
            new_name='TypeCLient',
        ),
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='TypeIdentityClient',
            new_name='TypeDocument',
        ),
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='ciiuClient',
            new_name='ciiu',
        ),
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='legalRepresentativeEmail',
            new_name='foreignCurrencyAccountBank',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='foreignTaxObligationDescriptionNP',
            new_name='activityDescription',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='foreignTaxObligationNP',
            new_name='foreignTaxObligation',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='publicPersonRelationDescriptionNP',
            new_name='foreignTaxObligationDescription',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='handlePublicResourcesNP',
            new_name='handlePublicResources',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='publicPersonRelationNP',
            new_name='publicPersonRelation',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='publicRecognitionNP',
            new_name='publicRecognition',
        ),
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='legalRepresentativeTel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='socialReason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='termsAndConditions',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='TypeCLient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.typeclient'),
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='publicPersonRelationDescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='termsAndConditions',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='typeProducts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
