# Generated by Django 4.1 on 2022-10-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0024_alter_legalclientselfmanagement_laftriskprevention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='department',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.department'),
            preserve_default=False,
        ),
    ]
