# Generated by Django 4.1 on 2022-10-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_broker_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalclientselfmanagement',
            old_name='typeCLient',
            new_name='typeClient',
        ),
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='TypeCLient',
            new_name='typeClient',
        ),
    ]
