# Generated by Django 4.1 on 2022-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0026_rename_typeclient_legalclientselfmanagement_typeclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='legalRepresentativeCitizenship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='legalRepresentativeCitizenship', to='misc.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='legalRepresentativeEmail',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='legalRepresentativeLastName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.broker'),
        ),
    ]
