# Generated by Django 4.1 on 2022-10-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0027_legalclientselfmanagement_legalrepresentativecitizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclientselfmanagement',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='countryLC', to='misc.country'),
            preserve_default=False,
        ),
    ]
