# Generated by Django 4.1 on 2022-10-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_legalclientselfmanagement_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
