# Generated by Django 4.1 on 2022-10-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_add_type_period'),
        ('client', '0030_naturalclientselfmanagement_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='typePeriod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.typeperiod'),
            preserve_default=False,
        ),
    ]
