# Generated by Django 4.1 on 2022-11-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0031_financialprofile_typeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='typeVinculation',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrencyAccountBank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrencyAccountNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrencyAccounts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrencyCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreignCurrencyCountry', to='misc.country'),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='foreignCurrencyOperations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='typeForeignCurrencyAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.accounttype'),
        ),
    ]
