# Generated by Django 4.1 on 2022-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_naturalclientselfmanagement_typevinculation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='document_number',
            field=models.CharField(error_messages={'unique': 'este documento ya se encuentra registrado. - cliente'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='email',
            field=models.CharField(error_messages={'unique': 'este correo ya se encuentra registrado. - cliente'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='legalclientselfmanagement',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'este telefono ya se encuentra registrado. - cliente'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='documentNumber',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente con este número de documento.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='email',
            field=models.EmailField(error_messages={'unique': 'este correo ya se encuentra registrado.'}, max_length=255, unique=True),
        ),
    ]
