# Generated by Django 4.1 on 2022-11-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0033_alter_legalclientselfmanagement_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciiu_company', to='misc.ciiu'),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyActivity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyCity', to='misc.city'),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyDepartment', to='misc.department'),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyPhone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='companyRole',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
