# Generated by Django 4.1 on 2022-11-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0034_alter_naturalclientselfmanagement_ciiu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naturalclientselfmanagement',
            old_name='referenceCompanyCity',
            new_name='referenceCity',
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='bankReferenceDepartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bankReferenceDepartment', to='misc.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalclientselfmanagement',
            name='referenceDepartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='referenceDepartment', to='misc.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='typeProducts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
