# Generated by Django 4.1 on 2022-11-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_rename_referencecompanycity_naturalclientselfmanagement_referencecity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='documentExpedition',
            field=models.CharField(max_length=255),
        ),
    ]
