# Generated by Django 4.1 on 2022-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_alter_naturalclientselfmanagement_documentexpedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='foreignTaxObligation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='handlePublicResources',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='publicPersonRelation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='publicRecognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='naturalclientselfmanagement',
            name='termsAndConditions',
            field=models.BooleanField(default=False),
        ),
    ]
