# Generated by Django 4.1 on 2022-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_alter_naturalclientselfmanagement_foreigntaxobligation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(max_length=255),
        ),
    ]
