# Generated by Django 4.1 on 2022-12-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0038_alter_client_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='observations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(error_messages={'required': 'El número de identificación es requerido'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(error_messages={'unique': 'este correo ya se encuentra registrado.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'este telefono ya se encuentra registrado.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(error_messages={'required': 'El tipo de cliente es requerido'}, on_delete=django.db.models.deletion.CASCADE, to='misc.typeclient'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_identity',
            field=models.ForeignKey(error_messages={'required': 'El tipo de identificación es requerido'}, on_delete=django.db.models.deletion.CASCADE, to='misc.typeidentity'),
        ),
    ]
