# Generated by Django 4.1 on 2022-12-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0040_legalclient_principalproviders_principalproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='bankReferenceCity',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='bankReferenceDepartment',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='ciiu',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='city',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='companyCity',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='companyDepartment',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='country',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='referenceCity',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='referenceDepartment',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='typeClient',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='typeDocument',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='user_created_at',
        ),
        migrations.RemoveField(
            model_name='naturalclientselfmanagement',
            name='user_updated_at',
        ),
        migrations.DeleteModel(
            name='LegalClientSelfManagement',
        ),
        migrations.DeleteModel(
            name='NaturalClientSelfManagement',
        ),
    ]
