# Generated by Django 4.1 on 2022-12-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_remove_naturalclientselfmanagement_bankreferencecity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='publicPersonLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalproducts',
            name='legalClient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.legalclient'),
            preserve_default=False,
        ),
    ]
