# Generated by Django 4.1 on 2022-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0042_legalclient_publicpersonlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
