# Generated by Django 4.1 on 2022-12-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0043_legalclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.ciiu'),
        ),
    ]
