# Generated by Django 4.1 on 2022-12-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('client', '0044_legalclient_ciiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalclient',
            name='ciiu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.ciiu'),
            preserve_default=False,
        ),
    ]
