# Generated by Django 4.1 on 2022-12-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_alter_legalclient_ciiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersandshareholders',
            name='type',
        ),
    ]
