# Generated by Django 4.1 on 2022-12-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0022_period_range_values'),
        ('client', '0046_remove_partnersandshareholders_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalClient',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('documentNumber', models.CharField(error_messages={'unique': 'Ya existe un cliente con este documento'}, max_length=255, unique=True)),
                ('dateOfExpedition', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('companyPhone', models.CharField(blank=True, max_length=255, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('typeProducts', models.CharField(blank=True, max_length=255, null=True)),
                ('mensualIncome', models.CharField(blank=True, max_length=255, null=True)),
                ('mensualExpenses', models.CharField(blank=True, max_length=255, null=True)),
                ('assets', models.CharField(blank=True, max_length=255, null=True)),
                ('passives', models.CharField(blank=True, max_length=255, null=True)),
                ('patrimony', models.CharField(blank=True, max_length=255, null=True)),
                ('otherIncome', models.CharField(blank=True, max_length=255, null=True)),
                ('conceptOtherIncome', models.CharField(blank=True, max_length=255, null=True)),
                ('managePublicResources', models.BooleanField(default=False)),
                ('publicRecognition', models.BooleanField(default=False)),
                ('publicPersonRecognition', models.BooleanField(default=False)),
                ('publicPersonRecognitionDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('foreignTax', models.BooleanField(default=False)),
                ('foreignTaxDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('referencePhone', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceBank', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceBankPhone', models.CharField(blank=True, max_length=255, null=True)),
                ('referenceBankProduct', models.CharField(blank=True, max_length=255, null=True)),
                ('termsAndConditions', models.BooleanField(default=False)),
                ('ciiu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.ciiu')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.city')),
                ('companyCity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_company_city', to='misc.city')),
                ('companyDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_company_department', to='misc.department')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.department')),
                ('referenceBankCity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_reference_bank_city', to='misc.city')),
                ('referenceBankDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_reference_bank_department', to='misc.department')),
                ('referenceCity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_reference_city', to='misc.city')),
                ('referenceDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_reference_department', to='misc.department')),
                ('typeDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.typeidentity')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
