# Generated by Django 4.1 on 2022-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0048_naturalclient_activitytype_naturalclient_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
