# Generated by Django 4.1 on 2022-12-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0022_period_range_values'),
        ('client', '0049_naturalclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='periodRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.periodrange'),
        ),
    ]
