# Generated by Django 4.1 on 2022-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_financialprofile_periodrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
