# Generated by Django 4.1 on 2022-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_contact_email_contact_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(error_messages={'unique': 'este correo ya se encuentra registrado.'}, max_length=255),
        ),
    ]
