# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0053_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ['-created_at'], 'verbose_name': 'assets', 'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['-created_at'], 'verbose_name': 'brokers', 'verbose_name_plural': 'brokers'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'clients', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='financialcentral',
            options={'ordering': ['-created_at'], 'verbose_name': 'FinancialCentrals', 'verbose_name_plural': 'FinancialCentrals'},
        ),
        migrations.AlterModelOptions(
            name='financialprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'FinancialProfiles', 'verbose_name_plural': 'FinancialProfiles'},
        ),
        migrations.AlterModelOptions(
            name='legalclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'legalClient', 'verbose_name_plural': 'legalClient'},
        ),
        migrations.AlterModelOptions(
            name='legalrepresentative',
            options={'ordering': ['-created_at'], 'verbose_name': 'legalRepresentatives', 'verbose_name_plural': 'legalRepresentatives'},
        ),
        migrations.AlterModelOptions(
            name='naturalclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'naturalClient', 'verbose_name_plural': 'naturalClient'},
        ),
        migrations.AlterModelOptions(
            name='overview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Overviews', 'verbose_name_plural': 'Overviews'},
        ),
        migrations.AlterModelOptions(
            name='passives',
            options={'ordering': ['-created_at'], 'verbose_name': 'passives', 'verbose_name_plural': 'passives'},
        ),
        migrations.AlterModelOptions(
            name='patrimony',
            options={'ordering': ['-created_at'], 'verbose_name': 'patrimony', 'verbose_name_plural': 'patrimony'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'requests', 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterModelOptions(
            name='riskprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'riskProfile', 'verbose_name_plural': 'riskProfiles'},
        ),
        migrations.AlterModelOptions(
            name='stateofresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'stateOfResult', 'verbose_name_plural': 'stateOfResult'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'este teléfono ya se encuentra registrado.'}, max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='legalclient',
            table='legalClient',
        ),
        migrations.AlterModelTable(
            name='naturalclient',
            table='naturalClient',
        ),
    ]
