# Generated by Django 4.1 on 2023-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0058_alter_client_email_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
