# Generated by Django 4.1 on 2023-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0059_alter_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
