# Generated by Django 4.1 on 2023-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0060_alter_account_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='periodDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
