# Generated by Django 4.1 on 2023-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0061_financialprofile_perioddays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='periodDays',
            field=models.IntegerField(default=0),
        ),
    ]
