# Generated by Django 4.1 on 2023-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0062_alter_financialprofile_perioddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='periodEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='periodStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
