# Generated by Django 4.1 on 2023-01-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0029_receiptstatus'),
        ('client', '0063_financialprofile_periodenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.ciiu'),
        ),
    ]
