# Generated by Django 4.1 on 2023-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0064_alter_client_ciiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='document_number',
            field=models.CharField(error_messages={'unique': 'El número de documento ya existe'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.CharField(error_messages={'unique': 'El correo electrónico ya existe'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'El número de teléfono ya existe'}, max_length=255, unique=True),
        ),
    ]
