# Generated by Django 4.1 on 2023-01-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0065_alter_broker_document_number_alter_broker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='periodDays',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
