# Generated by Django 4.1 on 2023-01-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0030_add_new_receiptStatus'),
        ('client', '0066_alter_financialprofile_perioddays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.accounttype'),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.bank'),
        ),
    ]
