# Generated by Django 4.1.7 on 2023-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_alter_riskprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='typeVinculation',
            field=models.IntegerField(default=0),
        ),
    ]
