# Generated by Django 4.1.7 on 2023-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0068_naturalclient_typevinculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='birthDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalclient',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe un cliente con este correo'}, max_length=255, null=True, unique=True),
        ),
    ]
