# Generated by Django 4.1.7 on 2023-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0069_naturalclient_birthdate_naturalclient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='referenceCompany',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
