# Generated by Django 4.1.7 on 2023-04-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0031_add_accounting_account'),
        ('client', '0070_naturalclient_referencecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_client_country_of_birth', to='misc.country'),
        ),
    ]
