# Generated by Django 4.1.7 on 2023-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0071_legalclient_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
