# Generated by Django 4.1.7 on 2023-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0073_legalclientdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalclientdocuments',
            name='document',
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='idRequest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='idSignature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='signStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legalclientdocuments',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
