# Generated by Django 4.1.7 on 2023-04-13 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0074_remove_legalclientdocuments_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalClientDocuments',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('idRequest', models.CharField(blank=True, max_length=255, null=True)),
                ('idSignature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('signStatus', models.IntegerField(default=0)),
                ('naturalClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.naturalclient')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
