# Generated by Django 4.1.7 on 2023-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0075_naturalclientdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='mainEmail',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe un cliente con este correo'}, max_length=255, null=True, unique=True),
        ),
    ]
