# Generated by Django 4.1.7 on 2023-05-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0032_typeidentity_abbreviation'),
        ('client', '0076_naturalclient_mainemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='dianAccountState',
            field=models.FileField(blank=True, null=True, upload_to='clients/dianAccountState'),
        ),
        migrations.AddField(
            model_name='legalclient',
            name='legalRepresentativeDocumentFile',
            field=models.FileField(blank=True, null=True, upload_to='clients/legalRepresentativeDocumentFile'),
        ),
        migrations.AddField(
            model_name='legalclient',
            name='rut',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalclient',
            name='homePhone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='naturalclient',
            name='secondaryCiiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_client_secondary_ciiu', to='misc.ciiu'),
        ),
    ]
