# Generated by Django 4.1.7 on 2023-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0077_legalclient_dianaccountstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='rutFile',
            field=models.FileField(blank=True, null=True, upload_to='clients/rutFile'),
        ),
    ]
