# Generated by Django 4.1.7 on 2023-05-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0078_legalclient_rutfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalclient',
            name='rut',
        ),
    ]
