# Generated by Django 4.1.7 on 2023-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0079_remove_legalclient_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalclient',
            name='numberOfEmployees',
            field=models.CharField(max_length=255),
        ),
    ]
