# Generated by Django 4.1.7 on 2023-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0080_alter_legalclient_numberofemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalclient',
            name='bankCertificationFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='naturalclient',
            name='documentFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='naturalclient',
            name='rentDeclarationFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
