# Generated by Django 4.1.7 on 2023-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0081_naturalclient_bankcertificationfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='legalRepresentativeIdFile',
            field=models.FileField(blank=True, null=True, upload_to='clients/legalRepresentativeIdFile'),
        ),
        migrations.AlterField(
            model_name='legalclient',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un cliente con este correo'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='naturalclient',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe un cliente con este correo'}, max_length=255, null=True),
        ),
    ]
