# Generated by Django 4.1.2 on 2023-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0082_legalclient_legalrepresentativeidfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalclient',
            name='descriptionAndInformation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalclient',
            name='shareholdingStructure',
            field=models.FileField(blank=True, null=True, upload_to='clients/shareholdingStructure'),
        ),
    ]
