# Generated by Django 4.1.2 on 2023-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0083_legalclient_descriptionandinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalclient',
            name='mainEmail',
            field=models.EmailField(blank=True, default=None, error_messages={'unique': 'Ya existe un cliente con este correo'}, max_length=255),
            preserve_default=False,
        ),
    ]
