# Generated by Django 4.1.2 on 2023-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0084_alter_naturalclient_mainemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalclient',
            name='documentNumber',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente con este documento'}, max_length=255),
        ),
    ]
