# Generated by Django 4.1.2 on 2023-07-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0032_typeidentity_abbreviation'),
        ('client', '0086_alter_naturalclient_activitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrepresentative',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.department'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.city'),
        ),
        migrations.AlterField(
            model_name='legalrepresentative',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.city'),
        ),
    ]
