# Generated by Django 4.1.2 on 2023-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0087_legalrepresentative_department_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcentral',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
