# Generated by Django 4.1.2 on 2024-08-06 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0088_alter_financialcentral_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('old_balance', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('amount_changed', models.FloatField()),
                ('operation_type', models.CharField(choices=[('deposit', 'Deposit'), ('pre_operation', 'PreOperation'), ('refund', 'Refund'), ('buy_order', 'BuyOrderWH'), ('adjustment', 'Adjustment')], max_length=20)),
                ('operation_id', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='client.account')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Balance History',
                'verbose_name_plural': 'Account Balance Histories',
                'db_table': 'account_balance_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
