# Generated by Django 4.1.2 on 2026-01-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0090_client_profile_image_client_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRisk',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('min_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('level', models.CharField(default='No aplica', max_length=255)),
                ('interpretation', models.TextField(default='No aplica')),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.riskprofile')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'levelRisk',
                'verbose_name_plural': 'levelRisks',
                'db_table': 'levelRisk',
                'ordering': ['-created_at'],
            },
        ),
    ]
