# Generated by Django 4.1.2 on 2026-01-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0091_levelrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelrisk',
            name='risk_profile',
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='riskLevels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.levelrisk'),
        ),
    ]
