# Generated by Django 4.1.2 on 2026-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0092_remove_levelrisk_risk_profile_riskprofile_risklevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelrisk',
            name='score_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
