# Generated by Django 4.1.2 on 2026-01-15 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0093_levelrisk_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRole',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('state', models.IntegerField(default=1)),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clientRole',
                'verbose_name_plural': 'clientRoles',
                'db_table': 'clientRoles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRoleAssignment',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='clients_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='client.client')),
                ('role', models.ForeignKey(db_column='clientroles_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='client.clientrole')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client_role_assignment',
                'verbose_name_plural': 'client_role_assignments',
                'db_table': 'client_role_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientroleassignment',
            constraint=models.UniqueConstraint(fields=('client', 'role'), name='uniq_client_role_assignment'),
        ),
    ]
