# Generated by Django 4.1.2 on 2026-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0094_clientrole_clientroleassignment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['client', 'created_at'], name='idx_account_client_created'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['state', '-created_at'], name='idx_client_state_created'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['document_number'], name='idx_client_document'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['social_reason'], name='idx_client_social_reason'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name'], name='idx_client_first_name'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name'], name='idx_client_last_name'),
        ),
        migrations.AddIndex(
            model_name='clientrole',
            index=models.Index(fields=['state', 'name'], name='idx_clientrole_state_name'),
        ),
        migrations.AddIndex(
            model_name='clientrole',
            index=models.Index(fields=['name'], name='idx_clientrole_name'),
        ),
        migrations.AddIndex(
            model_name='clientroleassignment',
            index=models.Index(fields=['client', 'role'], name='idx_roleassign_client_role'),
        ),
        migrations.AddIndex(
            model_name='clientroleassignment',
            index=models.Index(fields=['client'], name='idx_roleassign_client'),
        ),
        migrations.AddIndex(
            model_name='clientroleassignment',
            index=models.Index(fields=['role'], name='idx_roleassign_role'),
        ),
    ]
