# Generated by Django 4.1 on 2022-09-28 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0004_delete_preoperation'),
        ('client', '0016_alter_financialcentral_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0008_add_type_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOperation',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('opId', models.CharField(max_length=255)),
                ('opDate', models.DateField()),
                ('applyGm', models.BooleanField(default=False)),
                ('billFraction', models.IntegerField(default=0)),
                ('DateBill', models.DateField()),
                ('DateExpiration', models.DateField()),
                ('probableDate', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('payedAmount', models.IntegerField(default=0)),
                ('discountTax', models.FloatField(default=0)),
                ('investorTax', models.FloatField(default=0)),
                ('operationDays', models.IntegerField(blank=True, null=True)),
                ('presentValueInvestor', models.FloatField(default=0)),
                ('presentValueSF', models.FloatField(default=0)),
                ('investorProfit', models.FloatField(default=0)),
                ('commissionSF', models.FloatField(default=0)),
                ('GM', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsBill', to='bill.bill')),
                ('clientAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorAccount', to='client.account')),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitter', to='client.client')),
                ('emitterBroker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitterBroker', to='client.broker')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestor', to='client.client')),
                ('investorBroker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorBroker', to='client.broker')),
                ('opType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.typeoperation')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsPayer', to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PreOperation',
                'verbose_name_plural': 'PreOperations',
                'db_table': 'preOperation',
            },
        ),
    ]
