# Generated by Django 4.1 on 2022-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperation',
            name='opPendingAmount',
            field=models.FloatField(default=0),
        ),
    ]
