# Generated by Django 4.1 on 2022-10-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_delete_preoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_preoperation_oppendingamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('typeReceipt', models.IntegerField(default=0)),
                ('payedAmount', models.FloatField(default=0)),
                ('investorInterests', models.FloatField(default=0)),
                ('tableInterests', models.FloatField(default=0)),
                ('additionalDays', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.preoperation')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'ordering': ['created_at'],
            },
        ),
    ]
