# Generated by Django 4.1 on 2022-10-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_buyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='idRequest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
