# Generated by Django 4.1 on 2022-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_buyorder_date_alter_buyorder_idrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='idSignature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
