# Generated by Django 4.1 on 2022-11-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_buyorder_idsignature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preoperation',
            options={'verbose_name': 'operation', 'verbose_name_plural': 'operations'},
        ),
        migrations.AddField(
            model_name='preoperation',
            name='payedPercent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='billFraction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payedAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='preoperation',
            table='operation',
        ),
    ]
