# Generated by Django 4.1 on 2022-11-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_alter_client_document_number'),
        ('misc', '0020_remove_accounttypelog_user_remove_activitylog_user_and_more'),
        ('bill', '0005_bill_other_ret_billevent_date_alter_creditnote_total'),
        ('operation', '0008_alter_preoperation_options_preoperation_payedpercent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperation',
            name='DateBill',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='DateExpiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='GM',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='additionalInterests',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='applyGm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsBill', to='bill.bill'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='clientAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorAccount', to='client.account'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='commissionSF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='discountTax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='emitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitter', to='client.client'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='emitterBroker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitterBroker', to='client.broker'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestor', to='client.client'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorBroker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorBroker', to='client.broker'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorInterests',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorProfit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorTax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opPendingAmount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.typeoperation'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payedAmount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payedPercent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsPayer', to='client.client'),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='presentValueInvestor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='presentValueSF',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='probableDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='tableInterests',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
