# Generated by Django 4.1 on 2022-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_preoperation_datebill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperation',
            name='opExpiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
