# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_preoperation_opexpiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'BuyOrder', 'verbose_name_plural': 'BuyOrders'},
        ),
        migrations.AlterModelOptions(
            name='preoperation',
            options={'ordering': ['-created_at'], 'verbose_name': 'operation', 'verbose_name_plural': 'operations'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
    ]
