# Generated by Django 4.1 on 2023-01-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0025_alter_city_options_alter_department_options'),
        ('bill', '0008_alter_bill_options_alter_billevent_options_and_more'),
        ('client', '0058_alter_client_email_alter_client_phone_number'),
        ('operation', '0011_alter_buyorder_options_alter_preoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperation',
            name='DateBill',
            field=models.DateField(default=None, error_messages={'required': 'La fecha de la factura es requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='DateExpiration',
            field=models.DateField(default=None, error_messages={'required': 'La fecha de vencimiento es requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='GM',
            field=models.FloatField(default=0, error_messages={'required': 'La GM es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='amount',
            field=models.FloatField(default=0, error_messages={'required': 'El monto es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='bill',
            field=models.ForeignKey(default=None, error_messages={'required': 'La factura es requerida'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsBill', to='bill.bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='clientAccount',
            field=models.ForeignKey(default=None, error_messages={'required': 'La cuenta del inversionista es requerida'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorAccount', to='client.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='commissionSF',
            field=models.FloatField(default=0, error_messages={'required': 'La comisión del SF es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='discountTax',
            field=models.FloatField(default=0, error_messages={'required': 'El descuento de impuestos es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='emitter',
            field=models.ForeignKey(default=None, error_messages={'required': 'El emisor es requerido'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitter', to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='emitterBroker',
            field=models.ForeignKey(default=None, error_messages={'required': 'El corredor del emisor es requerido'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsEmitterBroker', to='client.broker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investor',
            field=models.ForeignKey(default=None, error_messages={'required': 'El inversionista es requerido'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestor', to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorBroker',
            field=models.ForeignKey(default=None, error_messages={'required': 'El corredor del inversionista es requerido'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsInvestorBroker', to='client.broker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorProfit',
            field=models.FloatField(default=0, error_messages={'required': 'El beneficio del inversionista es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='investorTax',
            field=models.FloatField(default=0, error_messages={'required': 'El impuesto del inversionista es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opDate',
            field=models.DateField(default=None, error_messages={'required': 'La fecha de la operación es requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opExpiration',
            field=models.DateField(default=None, error_messages={'required': 'La fecha de vencimiento de la operación es requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opPendingAmount',
            field=models.FloatField(default=0, error_messages={'required': 'El monto pendiente de la operación es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='opType',
            field=models.ForeignKey(default=None, error_messages={'required': 'El tipo de operación es requerido'}, on_delete=django.db.models.deletion.CASCADE, to='misc.typeoperation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='operationDays',
            field=models.IntegerField(default=None, error_messages={'required': 'Los días de la operación es requerido'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payedAmount',
            field=models.FloatField(default=0, error_messages={'required': 'El monto pagado es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payedPercent',
            field=models.FloatField(default=0, error_messages={'required': 'El porcentaje pagado es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='payer',
            field=models.ForeignKey(default=None, error_messages={'required': 'El pagador es requerido'}, on_delete=django.db.models.deletion.CASCADE, related_name='preOperationsPayer', to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='presentValueInvestor',
            field=models.FloatField(default=0, error_messages={'required': 'El valor presente del inversionista es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='presentValueSF',
            field=models.FloatField(default=0, error_messages={'required': 'El valor presente del SF es requerido'}),
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='probableDate',
            field=models.DateField(default=None, error_messages={'required': 'La fecha probable es requerida'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preoperation',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
