# Generated by Django 4.1 on 2023-01-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_receipt_futurevaluerecalculation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='bill',
        ),
    ]
