# Generated by Django 4.1 on 2023-01-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_remove_receipt_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='status',
            new_name='dId',
        ),
        migrations.AddField(
            model_name='receipt',
            name='realDays',
            field=models.IntegerField(default=0),
        ),
    ]
