# Generated by Django 4.1 on 2023-01-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0060_alter_account_state'),
        ('operation', '0015_rename_status_receipt_did_receipt_realdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.account'),
            preserve_default=False,
        ),
    ]
