# Generated by Django 4.1 on 2023-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_receipt_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='gmvValue',
            new_name='additionalInterestsSM',
        ),
        migrations.AddField(
            model_name='receipt',
            name='calculatedDays',
            field=models.IntegerField(default=0),
        ),
    ]
