# Generated by Django 4.1 on 2023-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_rename_gmvvalue_receipt_additionalinterestssm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
