# Generated by Django 4.1 on 2023-01-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0030_add_new_receiptStatus'),
        ('operation', '0018_receipt_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receiptStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.receiptstatus'),
        ),
    ]
