# Generated by Django 4.1 on 2023-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_receipt_receiptstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperation',
            name='insufficientAccountBalance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
