# Generated by Django 4.1.2 on 2023-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_preoperation_insufficientaccountbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperation',
            name='isRebuy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
