# Generated by Django 4.1.2 on 2023-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_preoperation_isrebuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='presentValueInvestor',
            field=models.FloatField(default=0),
        ),
    ]
