# Generated by Django 4.1.2 on 2023-07-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_alter_receipt_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preoperation',
            name='additionalInterests',
        ),
        migrations.RemoveField(
            model_name='preoperation',
            name='investorInterests',
        ),
        migrations.RemoveField(
            model_name='preoperation',
            name='tableInterests',
        ),
    ]
