# Generated by Django 4.1.2 on 2023-11-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_remove_preoperation_additionalinterests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorder',
            options={'ordering': ['-date'], 'verbose_name': 'BuyOrder', 'verbose_name_plural': 'BuyOrders'},
        ),
        migrations.RenameField(
            model_name='buyorder',
            old_name='idRequest',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='buyorder',
            old_name='idSignature',
            new_name='name',
        ),
    ]
