# Generated by Django 4.1.2 on 2026-01-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_integrationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preoperation',
            options={'ordering': ['-opDate', '-opId'], 'verbose_name': 'operation', 'verbose_name_plural': 'operations'},
        ),
    ]
