# Generated by Django 4.1.2 on 2026-04-21 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0027_alter_preoperation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('opId', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SINGLE', 'Single Operation'), ('BULK', 'Bulk Operation'), ('UPLOAD_EXCEL', 'Upload Excel'), ('REGISTER_FROM_UPLOAD', 'Register From Upload'), ('PATCH', 'Patch Operation'), ('DELETE', 'Delete Operation'), ('BILL', 'Bill')], max_length=40)),
                ('action', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('PARTIAL', 'Partial'), ('INFO', 'Info')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('bill_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_id_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='operation.preoperation')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operation log',
                'verbose_name_plural': 'operation logs',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
