# Generated by Django 4.1.2 on 2026-04-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0094_clientrole_clientroleassignment_and_more'),
        ('misc', '0035_typeevent_diandescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0028_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassiveOperationDraft',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('opId', models.BigIntegerField(blank=True, null=True)),
                ('opDate', models.DateField(blank=True, null=True)),
                ('currentStep', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('READY_FOR_EXCEL', 'Listo para Excel'), ('REGISTERED', 'Registrado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=30)),
                ('selectedBills', models.JSONField(blank=True, default=list)),
                ('investorAssignments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('registeredOpId', models.BigIntegerField(blank=True, null=True)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('emitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='massive_drafts_emitter', to='client.client')),
                ('emitterBroker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.broker')),
                ('opType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.typeoperation')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='massive_drafts_payer', to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'massive_operation_draft',
                'ordering': ['-updated_at'],
            },
        ),
    ]
