# Generated by Django 4.1.2 on 2026-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_massiveoperationdraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massiveoperationdraft',
            options={},
        ),
        migrations.AddIndex(
            model_name='massiveoperationdraft',
            index=models.Index(fields=['state', 'user_created_at', 'status', '-updated_at', '-created_at'], name='massive_draft_list_idx'),
        ),
        migrations.AlterModelTable(
            name='massiveoperationdraft',
            table=None,
        ),
    ]
