# Generated by Django 4.1.2 on 2026-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_alter_massiveoperationdraft_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['emitter', '-created_at'], name='idx_operation_emitter_created'),
        ),
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['payer', '-created_at'], name='idx_operation_payer_created'),
        ),
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['investor', '-created_at'], name='idx_operation_investor_created'),
        ),
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['emitter'], name='idx_operation_emitter'),
        ),
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['payer'], name='idx_operation_payer'),
        ),
        migrations.AddIndex(
            model_name='preoperation',
            index=models.Index(fields=['investor'], name='idx_operation_investor'),
        ),
    ]
