# Generated by Django 4.1 on 2022-09-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_add_type_events'),
        ('bill', '0002_billevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billevent',
            name='description',
        ),
        migrations.AlterField(
            model_name='billevent',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='misc.typeevent'),
            preserve_default=False,
        ),
    ]
