# Generated by Django 4.1 on 2022-09-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_billevent_date_remove_billevent_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreOperation',
        ),
    ]
