# Generated by Django 4.1 on 2022-10-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_delete_preoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='other_ret',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billevent',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='total',
            field=models.FloatField(),
        ),
    ]
