# Generated by Django 4.1 on 2022-12-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_bill_other_ret_billevent_date_alter_creditnote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billId',
            field=models.CharField(error_messages={'unique': 'Ya existe una factura con este número'}, max_length=255, unique=True),
        ),
    ]
