# Generated by Django 4.1 on 2022-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_alter_bill_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cufe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
