# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_alter_bill_cufe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='billevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['-created_at']},
        ),
    ]
