# Generated by Django 4.1 on 2023-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_bill_options_alter_billevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reBuyAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
