# Generated by Django 4.1 on 2023-01-27 20:37

from django.db import migrations


class Migration(migrations.Migration):
    def load_initial_data(apps, schema_editor):
        model = apps.get_model('misc', 'typeEvent')
        model.objects.create(id='61d17930-d945-4c41-a3bf-d84dbfb4dc24', description='Acuse de Recibo de la FEV', code='01')
        model.objects.create(id='ac8cbb6a-078b-4ce0-ab8d-e97298f5f0e4', description='Recibo del bien o prestación del servicio', code='02')
        model.objects.create(id='81c989f7-b43d-4b7d-9be1-9e0c90037aa7', description='Aceptación Expresa de la FEV', code='03')
        model.objects.create(id='1c002c99-4bc3-4cfb-b003-753f834ab777', description='Aceptación Tácita de la FEV', code='04')
        model.objects.create(id='a0e82dd1-1a9c-4ac5-b440-22a2ccbcd2ac', description='Reclamo de la FEV', code='05')
        model.objects.create(id='26f304a5-f592-4751-8db1-8d447121c487', description='Aval', code='06')
        model.objects.create(id='9814aa76-e81b-4e2e-ab1b-830bdfd76cc9', description='Inscripción en el RADIAN de la FEV TV', code='07')
        model.objects.create(id='9ce2fa4a-7c82-4b72-ae93-f520229380d2', description='Endoso electrónico en propiedad', code='08')
        model.objects.create(id='2c5075a7-9185-4171-91fd-6307074fae21', description='Endoso electrónico en garantía', code='09')
        model.objects.create(id='c3dd2aff-e6c0-4657-ac22-ff0265119ca4', description='Endoso electrónico en procuración', code='010')
        model.objects.create(id='62ed97e4-bfe6-4224-90d1-46608b3f72fe', description='Cancelación del endoso electrónico', code='011')
        model.objects.create(id='84cf2fb1-557d-48b4-85c7-fb261aa3816b', description='Limitación para circulación de la FEV TV', code='012')
        model.objects.create(id='fe6f4fe4-31e0-449b-9509-bba37360b2b3', description='Terminación de la Limitación para circulación de la FEV TV', code='013')
        model.objects.create(id='5a2b88b0-a9d8-4f63-8602-b6b0d8e12be1', description='Mandato', code='014')
        model.objects.create(id='a1a9a0fd-ca93-43cc-8d69-0762f8aabf31', description='Terminación del mandato', code='015')
        model.objects.create(id='89bab2c7-8f26-46b5-b0b9-db25cde1b82a', description='Informe para el pago', code='016')
        model.objects.create(id='8cf01a1f-df10-498b-9c8b-d08594ad776d', description='Pago de la FEV TV', code='017')
        model.objects.create(id='b8d4f8d3-aded-4b1f-873e-46c89a2538ed', description='Primera inscripción de la Factura Electrónica de Venta como Título Valor en el RADIAN para negociación general', code='036')
        model.objects.create(id='3ea77762-7208-457a-b035-70069ee42b5e', description='Endoso electrónico en propiedad con responsabilidad', code='037')
        model.objects.create(id='0e333b6b-27b1-4aaf-87ce-ad60af6e52e6', description='Endoso en garantía', code='038')
        model.objects.create(id='f5d475c0-4433-422f-b3d2-7964ea0aa5c4', description='Informe para el pago de la Factura Electrónica de Venta como Título Valor', code='046')
        model.objects.create(id='3bb86c74-1d1c-4986-a905-a47624b09322', description='Endoso con efectos de cesión ordinaria', code='047')
        model.objects.create(id='e76e9b7a-baeb-4972-b76e-3a8ce2d4fa30', description='Aceptación tácita de la Factura Electrónica de Venta', code='034')

    dependencies = [
        ('bill', '0009_bill_rebuyavailable'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
