# Generated by Django 4.1 on 2023-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_add_new_bill_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='billsFiles/')),
            ],
            options={
                'db_table': 'tempFile',
                'ordering': ['-bill'],
            },
        ),
    ]
