# Generated by Django 4.1 on 2023-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_tempfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
