# Generated by Django 4.1.2 on 2023-07-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_alter_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billId',
            field=models.CharField(error_messages={'unique': 'Ya existe una factura con este número'}, max_length=255),
        ),
    ]
