# Generated by Django 4.1.2 on 2023-07-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_alter_bill_billid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currentOwner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='endorsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='sameCurrentOwner',
            field=models.BooleanField(default=False),
        ),
    ]
