# Generated by Django 4.1.2 on 2023-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_alter_bill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='integrationCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
