# Generated by Django 4.1.2 on 2026-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_bill_integrationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
