# Generated by Django 4.1.2 on 2026-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_alter_billevent_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['emitterId'], name='idx_bill_emitter_id'),
        ),
    ]
