# Generated by Django 4.1.2 on 2026-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_bill_billy_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billyEventsConsecutiveErrors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='billyEventsLastAttemptAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billyEventsLastSuccessAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billyEventsNextCheckAt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
