# Generated by Django 4.1.2 on 2026-09-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0022_disable_invalid_billy_polling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='onWatchlist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='watchlistActivatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='watchlistActivatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billy_watchlist_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
