# Generated by Django 4.1 on 2022-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_emitterdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitterdeposit',
            name='beneficiary',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
