# Generated by Django 4.1 on 2022-10-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_accountingcontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emitterdeposit',
            options={'ordering': ['created_at'], 'verbose_name': 'emitterDeposit', 'verbose_name_plural': 'emitterDeposits'},
        ),
        migrations.AlterModelTable(
            name='emitterdeposit',
            table='emitterDeposits',
        ),
    ]
