# Generated by Django 4.1 on 2022-10-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_emitterdeposit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingcontrol',
            name='emitterDeposit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.emitterdeposit'),
            preserve_default=False,
        ),
    ]
