# Generated by Django 4.1 on 2022-10-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0018_rename_emitter_balance_account_balance_and_more'),
        ('misc', '0015_add_type_expenditure'),
        ('administration', '0007_accountingcontrol_emitterdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('gmAmount', models.FloatField()),
                ('beneficiary', models.CharField(max_length=255)),
                ('accountNumber', models.CharField(max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.account')),
                ('accountType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.accounttype')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_created_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_at', to=settings.AUTH_USER_MODEL)),
                ('user_updated_at', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'db_table': 'refunds',
                'ordering': ['created_at'],
            },
        ),
    ]
