# Generated by Django 4.1 on 2022-10-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_buyorder_idsignature'),
        ('administration', '0009_alter_emitterdeposit_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitterdeposit',
            name='operation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operation.preoperation'),
            preserve_default=False,
        ),
    ]
