# Generated by Django 4.1 on 2022-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_emitterdeposit_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='applyGM',
            field=models.BooleanField(default=False),
        ),
    ]
