# Generated by Django 4.1 on 2022-11-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_buyorder_idsignature'),
        ('administration', '0011_refund_applygm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitterdeposit',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.preoperation'),
        ),
    ]
