# Generated by Django 4.1 on 2022-12-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_emitterdeposit_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
