# Generated by Django 4.1 on 2022-12-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_deposit_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitterdeposit',
            name='edId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='rId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
