# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_emitterdeposit_edid_refund_rid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingcontrol',
            options={'ordering': ['-created_at'], 'verbose_name': 'accountingControl', 'verbose_name_plural': 'accountingControls'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'deposit', 'verbose_name_plural': 'deposits'},
        ),
        migrations.AlterModelOptions(
            name='emitterdeposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'emitterDeposit', 'verbose_name_plural': 'emitterDeposits'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'refund', 'verbose_name_plural': 'refunds'},
        ),
    ]
