# Generated by Django 4.1 on 2023-02-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0030_add_new_receiptStatus'),
        ('administration', '0015_alter_accountingcontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingcontrol',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.accountingaccount'),
        ),
        migrations.AlterField(
            model_name='accountingcontrol',
            name='emitterDeposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.emitterdeposit'),
        ),
        migrations.AlterField(
            model_name='accountingcontrol',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.typeexpenditure'),
        ),
    ]
