# Generated by Django 4.1.2 on 2023-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_accountingcontrol_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitterdeposit',
            name='accountNumber',
            field=models.CharField(max_length=255),
        ),
    ]
