# Generated by Django 4.1.2 on 2023-07-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0032_typeidentity_abbreviation'),
        ('administration', '0017_alter_emitterdeposit_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='accountType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.accounttype'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='applyGM',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.bank'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='gmAmount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
