# Generated by Django 4.1 on 2022-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at'], 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-created_at'], 'verbose_name': 'userRole', 'verbose_name_plural': 'userRoles'},
        ),
    ]
