name: Build & Deploy Testing

on:
  push:
    branches:
      - development

jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_TEST }}
          username: ${{ secrets.SSH_USERNAME_TEST }}
          key: ${{ secrets.SSH_KEY_TEST }}
          port: ${{ secrets.SSH_PORT_TEST }}
          script: |
            cd "${{secrets.TEST_FOLDER}}"
            git reset --hard
            git pull origin development
            echo "${{ secrets.DOT_ENV_TEST }}" > core/.env
            sudo docker compose -f docker-compose.test.yml --env-file docker.env up -d
            exit
